version: "3"

services:
  bot:
    container_name: minecat
    env_file: .env
    restart: always
    build: .
    volumes:
      - ./logs:/bot/logs
      - ./minecat:/bot/minecat
    environment:
      DB_URI: postgresql://postgres:postgres@postgres:5432/bot
    links:
      - postgres
      - manager
    depends_on:
      - postgres
      - manager
    ports:
      - "6900:6900"
      - "6901:6901"
  manager:
    container_name: manager
    restart: always
    build: ./manager
    volumes:
      - ./logs:/manager/logs
    ports:
      - "6899:6899"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
