version: "3"

x-restart-policy:
  &restart_policy
  restart: unless-stopped

services:
  bot:
    <<: *restart_policy
    deploy:
      replicas: ${TOTAL_CLUSTERS}
    depends_on:
      - postgres
      - keydb
      - manager
    build:
      context: .
      dockerfile: minecat/Dockerfile
    ports:
      - 127.0.0.1:${PORTS}:6969
    volumes:
      - ./logs:/bot/logs
      - ./minecat:/bot/minecat
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DB_URI: ${DB_URI:-postgresql://postgres:postgres@postgres:5432/bot}
      TOKEN: $TOKEN
      TOTAL_CLUSTERS: ${TOTAL_CLUSTERS:-1}
      TOTAL_SHARDS: ${TOTAL_SHARDS:-1}
  postgres:
    <<: *restart_policy
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  keydb:
    <<: *restart_policy
    image: eqalpha/keydb
  manager:
    <<: *restart_policy
    build:
      context: .
      dockerfile: manager/Dockerfile
    volumes:
      - ./logs:/manager/logs
    depends_on:
      - keydb
    ports:
      - 127.0.0.1:6899:6899
